logging:
    level:
        web: DEBUG
server:
    port: 8080
spring:
    application:
        name: spring-boot-lesson-example
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: pwd123
        url: jdbc:mysql://localhost:3306/e_learning
        username: fajar
    flyway:
        enabled: true
        locations: classpath:db/migration
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
        show-sql: true
